version: '3.8'

services:
  backend:
    build:
      context: ./exnaton-backend
      dockerfile: Dockerfile
    env_file:
      - ./exnaton-backend/.env
    ports:
      - "3001:3001"
    networks:
      - exnaton-network
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: root
      DB_PASSWORD: rootpassword
      DB_NAME: exnaton-energy

  frontend:
    build:
      context: ./exnaton-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - exnaton-network

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: exnaton-energy
    ports:
      - "5432:5432"
    networks:
      - exnaton-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  exnaton-network:

volumes:
  postgres_data:
